codecov:
  token: b747f973-f345-4855-b769-afb4a8814530

coverage:
  ignore:
    - test/
    - data/
    - mason_packages/
    - /usr/include/
    - *CMakeLists\.txt
    - *\.pb\.cc
    - *\.pb\.h
    - .clang-format
    - *\.proto
    - *\.md
    - .gitignore

comment:
  layout: "header, diff"
  behavior: default  # update if exists else create new
